"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { FileText,Upload,Download,CheckCircle2,ListTodo,Bell,ArrowLeft } from "lucide-react";
import { supabase } from "@/lib/supabase";
import "./workflow.css";

type Row=any;
export default function ClientWorkflowPage(){
 const [loading,setLoading]=useState(true),[user,setUser]=useState<any>(null),[client,setClient]=useState<Row>(null),[docs,setDocs]=useState<Row[]>([]),[approvals,setApprovals]=useState<Row[]>([]),[tasks,setTasks]=useState<Row[]>([]),[notifications,setNotifications]=useState<Row[]>([]),[notice,setNotice]=useState("");
 const [uploadTitle,setUploadTitle]=useState(""),[approvalNotes,setApprovalNotes]=useState<Record<string,string>>({});
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{const u=data.session?.user;if(!u){setLoading(false);return;}setUser(u);const {data:c}=await supabase.from("client_accounts").select("*").eq("user_id",u.id).maybeSingle();setClient(c);if(c)await load(c.id,u.id);setLoading(false);});},[]);
 async function load(clientId:string,userId:string){const [{data:d},{data:a},{data:t},{data:n}]=await Promise.all([supabase.from("client_documents").select("*").eq("client_id",clientId).order("created_at",{ascending:false}),supabase.from("client_approvals").select("*").eq("client_id",clientId).order("requested_at",{ascending:false}),supabase.from("client_tasks").select("*").eq("client_id",clientId).order("created_at",{ascending:false}),supabase.from("notifications").select("*").eq("user_id",userId).order("created_at",{ascending:false}).limit(50)]);setDocs(d||[]);setApprovals(a||[]);setTasks(t||[]);setNotifications(n||[])}
 async function openDoc(d:Row){const {data,error}=await supabase.storage.from("documents").createSignedUrl(d.storage_path,300);if(error){setNotice(error.message);return;}window.open(data.signedUrl,"_blank")}
 async function uploadDocument(file:File){if(!client||!user||!uploadTitle.trim())return;setNotice("Uploading...");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${client.id}/${Date.now()}-${safe}`;const {error}=await supabase.storage.from("documents").upload(path,file);if(error){setNotice(error.message);return;}const {data,error:e}=await supabase.from("client_documents").insert({client_id:client.id,uploaded_by:user.id,title:uploadTitle.trim(),document_type:"reference",storage_path:path,file_name:file.name,mime_type:file.type,file_size:file.size}).select().single();if(e){setNotice(e.message);return;}if(data)setDocs(x=>[data,...x]);setUploadTitle("");setNotice("Document uploaded to Forged Digital.")}
 async function respondApproval(a:Row,status:"approved"|"changes_requested"){const note=approvalNotes[a.id]||"";const {data,error}=await supabase.rpc("respond_to_client_approval",{p_approval_id:a.id,p_status:status,p_note:note||null});if(error){setNotice(error.message);return;}const updated=Array.isArray(data)?data[0]:data;setApprovals(x=>x.map(v=>v.id===a.id?{...v,...updated}:v));setNotice(status==="approved"?"Approval submitted.":"Change request submitted.")}
 async function updateTask(t:Row,status:string){const {data,error}=await supabase.rpc("update_client_task_status",{p_task_id:t.id,p_status:status});if(error){setNotice(error.message);return;}const updated=Array.isArray(data)?data[0]:data;setTasks(x=>x.map(v=>v.id===t.id?{...v,...updated}:v))}
 async function markRead(id:string){await supabase.from("notifications").update({is_read:true}).eq("id",id);setNotifications(x=>x.map(n=>n.id===id?{...n,is_read:true}:n))}
 async function markAll(){if(!user)return;await supabase.from("notifications").update({is_read:true}).eq("user_id",user.id).eq("is_read",false);setNotifications(x=>x.map(n=>({...n,is_read:true})))}
 if(loading)return <main className="cwf-gate">LOADING PROJECT HUB...</main>;
 if(!user)return <main className="cwf-gate"><Link href="/portal">CLIENT SIGN IN REQUIRED</Link></main>;
 return <main className="cwf-page"><header className="cwf-head"><Link href="/portal"><ArrowLeft size={16}/> PORTAL</Link><img src="/assets/forged-logo-wide.webp" alt="Forged Digital"/><Link href="/portal/billing">BILLING</Link></header><div className="cwf-shell"><div className="cwf-title"><p>PROJECT HUB</p><h1>{client?.company_name||"YOUR PROJECT"}</h1><span>Files, approvals, action items and project notifications in one place.</span></div>{notice&&<div className="cwf-notice">{notice}</div>}
 <section className="cwf-grid"><article className="cwf-card"><div className="cwf-card-head"><FileText/><div><p>DOCUMENTS</p><h2>Files & Contracts</h2></div></div><div className="cwf-upload-row"><input placeholder="What are you uploading?" value={uploadTitle} onChange={e=>setUploadTitle(e.target.value)}/><label><Upload size={14}/> UPLOAD<input type="file" onChange={e=>e.target.files?.[0]&&uploadDocument(e.target.files[0])}/></label></div><div className="cwf-list">{docs.length===0?<span>No documents yet.</span>:docs.map(d=><div key={d.id}><div><b>{d.title}</b><small>{d.document_type.toUpperCase()} · {d.file_name}</small></div><button onClick={()=>openDoc(d)}><Download size={13}/> OPEN</button></div>)}</div></article>
 <article className="cwf-card"><div className="cwf-card-head"><CheckCircle2/><div><p>APPROVALS</p><h2>Review & Respond</h2></div></div><div className="cwf-list approvals">{approvals.length===0?<span>No approval requests.</span>:approvals.map(a=><div key={a.id} className="approval-row"><div><b>{a.title}</b><small>{a.description||"No additional notes"}</small>{a.status==="pending"&&<textarea placeholder="Optional response notes" value={approvalNotes[a.id]||""} onChange={e=>setApprovalNotes({...approvalNotes,[a.id]:e.target.value})}/>}</div>{a.status==="pending"?<div className="approval-actions"><button onClick={()=>respondApproval(a,"approved")}>APPROVE</button><button className="secondary" onClick={()=>respondApproval(a,"changes_requested")}>REQUEST CHANGES</button></div>:<em className={`status ${a.status}`}>{a.status.replaceAll("_"," ")}</em>}</div>)}</div></article>
 <article className="cwf-card"><div className="cwf-card-head"><ListTodo/><div><p>ACTION ITEMS</p><h2>What Needs Doing</h2></div></div><div className="cwf-list">{tasks.length===0?<span>No action items.</span>:tasks.map(t=><div key={t.id}><div><b>{t.title}</b><small>{t.description||"No details"}{t.due_date?` · Due ${new Date(t.due_date+"T00:00:00").toLocaleDateString()}`:""}</small></div>{t.assigned_to==="client"?<select value={t.status} onChange={e=>updateTask(t,e.target.value)}><option value="open">Open</option><option value="in_progress">In Progress</option><option value="completed">Completed</option></select>:<em className={`status ${t.status}`}>{t.status.replaceAll("_"," ")}</em>}</div>)}</div></article>
 <article className="cwf-card"><div className="cwf-card-head"><Bell/><div><p>NOTIFICATIONS</p><h2>Project Activity</h2></div></div><div className="notification-head"><span>{notifications.filter(n=>!n.is_read).length} unread</span><button onClick={markAll}>MARK ALL READ</button></div><div className="cwf-list notifications">{notifications.length===0?<span>No notifications yet.</span>:notifications.map(n=><div key={n.id} className={n.is_read?"read":"unread"} onClick={()=>markRead(n.id)}><div><b>{n.title}</b><small>{n.body||n.kind} · {new Date(n.created_at).toLocaleString()}</small></div><i/></div>)}</div></article></section></div></main>
}
