"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Plus,Send,FileCheck2,Trash2,ReceiptText} from "lucide-react";
import {supabase} from "@/lib/supabase";
import "./proposals.css";

type Row=any; type Item={description:string;quantity:number;unit_amount:string};
const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format((c||0)/100);
export default function AdminProposals(){
 const [loading,setLoading]=useState(true),[allowed,setAllowed]=useState(false),[clients,setClients]=useState<Row[]>([]),[proposals,setProposals]=useState<Row[]>([]),[notice,setNotice]=useState("");
 const [clientId,setClientId]=useState(""),[title,setTitle]=useState("Website Design & Development"),[validUntil,setValidUntil]=useState(""),[taxRate,setTaxRate]=useState("0"),[discount,setDiscount]=useState("0"),[deposit,setDeposit]=useState("0"),[notes,setNotes]=useState(""),[terms,setTerms]=useState("Proposal pricing is valid through the date shown. Work begins after acceptance and any required deposit."),[items,setItems]=useState<Item[]>([{description:"Custom website design & development",quantity:1,unit_amount:"0.00"}]);
 const subtotal=useMemo(()=>items.reduce((s,i)=>s+Math.round((Number(i.unit_amount)||0)*100*(Number(i.quantity)||0)),0),[items]);
 const tax=Math.round(subtotal*(Number(taxRate)||0)/100),discountCents=Math.round((Number(discount)||0)*100),depositCents=Math.round((Number(deposit)||0)*100),total=Math.max(0,subtotal+tax-discountCents);
 async function load(){const {data:{session}}=await supabase.auth.getSession();if(!session){setLoading(false);return;}const {data:p}=await supabase.from("profiles").select("role").eq("id",session.user.id).single();if(p?.role!=="admin"){setLoading(false);return;}setAllowed(true);const [{data:c},{data:pr}]=await Promise.all([supabase.from("client_accounts").select("*").order("company_name"),supabase.from("proposals").select("*,client_accounts(company_name,contact_name,email),proposal_items(*)").order("created_at",{ascending:false})]);setClients(c||[]);setProposals(pr||[]);if(c?.[0]&&!clientId)setClientId(c[0].id);setLoading(false)}
 useEffect(()=>{load()},[]);
 function changeItem(n:number,key:keyof Item,value:string|number){setItems(cur=>cur.map((i,x)=>x===n?{...i,[key]:value}:i))}
 async function createProposal(){if(!clientId||!items.some(i=>i.description.trim()&&Number(i.unit_amount)>0)){setNotice("Choose a client and add at least one priced line item.");return;}setNotice("Creating proposal...");const {data:{user}}=await supabase.auth.getUser();const {data:proposal,error}=await supabase.from("proposals").insert({client_id:clientId,title,valid_until:validUntil||null,tax_rate:Number(taxRate)||0,discount_cents:discountCents,deposit_cents:depositCents,notes:notes||null,terms:terms||null,created_by:user?.id||null}).select().single();if(error||!proposal){setNotice(error?.message||"Could not create proposal.");return;}const rows=items.filter(i=>i.description.trim()).map((i,n)=>({proposal_id:proposal.id,position:n,description:i.description.trim(),quantity:Number(i.quantity)||1,unit_amount_cents:Math.round((Number(i.unit_amount)||0)*100)}));const {error:itemError}=await supabase.from("proposal_items").insert(rows);if(itemError){setNotice(itemError.message);return;}await supabase.rpc("recalculate_proposal_totals",{target_proposal:proposal.id});setNotice(`${proposal.proposal_number} created.`);setItems([{description:"Custom website design & development",quantity:1,unit_amount:"0.00"}]);setDiscount("0");setTaxRate("0");setDeposit("0");setNotes("");setValidUntil("");await load()}
 async function markSent(p:Row){const {error}=await supabase.from("proposals").update({status:"sent",sent_at:new Date().toISOString()}).eq("id",p.id);setNotice(error?error.message:`${p.proposal_number} sent to client.`);if(!error)await load()}
 async function convert(p:Row){const {data,error}=await supabase.rpc("convert_proposal_to_invoice",{target_proposal:p.id});setNotice(error?error.message:`${p.proposal_number} converted to invoice.`);if(!error)await load()}
 if(loading)return <main className="proposal-gate">LOADING PROPOSALS...</main>;
 if(!allowed)return <main className="proposal-gate"><h1>ADMIN ACCESS REQUIRED</h1><Link href="/portal">CLIENT LOGIN</Link></main>;
 return <main className="proposal-page"><header><Link href="/admin"><ArrowLeft size={16}/> BACK TO ADMIN</Link><img src="/assets/forged-logo-wide.webp" alt="Forged Digital"/><span>ESTIMATES & PROPOSALS</span></header><div className="proposal-shell">
 <section className="proposal-builder"><p className="eyebrow">SALES</p><h1>CREATE PROPOSAL</h1><div className="proposal-grid"><label><span>CLIENT</span><select value={clientId} onChange={e=>setClientId(e.target.value)}>{clients.map(c=><option key={c.id} value={c.id}>{c.company_name||c.contact_name||c.email}</option>)}</select></label><label><span>PROPOSAL TITLE</span><input value={title} onChange={e=>setTitle(e.target.value)}/></label><label><span>VALID UNTIL</span><input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label><label><span>DEPOSIT $</span><input type="number" min="0" step="0.01" value={deposit} onChange={e=>setDeposit(e.target.value)}/></label><label><span>TAX %</span><input type="number" min="0" step="0.01" value={taxRate} onChange={e=>setTaxRate(e.target.value)}/></label><label><span>DISCOUNT $</span><input type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)}/></label></div>
 <div className="line-items"><div className="line-head"><span>DESCRIPTION</span><span>QTY</span><span>RATE</span><span></span></div>{items.map((i,n)=><div className="line-row" key={n}><input value={i.description} onChange={e=>changeItem(n,"description",e.target.value)}/><input type="number" min="0.01" step="0.01" value={i.quantity} onChange={e=>changeItem(n,"quantity",e.target.value)}/><input type="number" min="0" step="0.01" value={i.unit_amount} onChange={e=>changeItem(n,"unit_amount",e.target.value)}/><button onClick={()=>setItems(cur=>cur.filter((_,x)=>x!==n))} disabled={items.length===1}><Trash2 size={15}/></button></div>)}<button className="add-line" onClick={()=>setItems(cur=>[...cur,{description:"",quantity:1,unit_amount:"0.00"}])}><Plus size={15}/> ADD LINE ITEM</button></div>
 <div className="proposal-bottom"><div><label><span>SCOPE / NOTES</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Scope, exclusions, deliverables, timing..."/></label><label><span>TERMS</span><textarea value={terms} onChange={e=>setTerms(e.target.value)}/></label></div><aside><p><span>SUBTOTAL</span><b>{money(subtotal)}</b></p><p><span>TAX</span><b>{money(tax)}</b></p><p><span>DISCOUNT</span><b>-{money(discountCents)}</b></p><p><span>DEPOSIT</span><b>{money(depositCents)}</b></p><p className="grand"><span>TOTAL</span><strong>{money(total)}</strong></p><button onClick={createProposal}>CREATE PROPOSAL</button></aside></div>{notice&&<div className="proposal-notice">{notice}</div>}</section>
 <section><p className="eyebrow">PIPELINE</p><h1>PROPOSALS</h1><div className="proposal-list">{proposals.length===0?<p className="empty">No proposals yet.</p>:proposals.map(p=><article key={p.id}><div><b>{p.proposal_number}</b><span>{p.client_accounts?.company_name||p.client_accounts?.contact_name||p.client_accounts?.email}</span><small>{p.status.toUpperCase()} · {p.title}{p.valid_until?` · valid through ${new Date(p.valid_until+"T00:00:00").toLocaleDateString()}`:""}</small>{p.response_notes&&<em>Client note: {p.response_notes}</em>}</div><div className="proposal-amount"><strong>{money(p.total_cents)}</strong><span>{p.deposit_cents>0?`${money(p.deposit_cents)} deposit`:"No deposit set"}</span></div><div className="proposal-actions">{p.status==="draft"&&<button onClick={()=>markSent(p)}><Send size={14}/> SEND</button>}{["accepted","sent","changes_requested"].includes(p.status)&&!p.converted_invoice_id&&<button onClick={()=>convert(p)}><ReceiptText size={14}/> CONVERT TO INVOICE</button>}{p.status==="accepted"&&<span className="accepted"><FileCheck2 size={14}/> ACCEPTED</span>}</div></article>)}</div></section>
 </div></main>;
}
