"use client";
import { ArrowRight, Link2, Settings, Shield, ShoppingCart, Users, Monitor } from "lucide-react";
import { useEffect, useState } from "react";
const services=[{icon:Monitor,title:"Web Design",text:"Custom, high-converting websites."},{icon:ShoppingCart,title:"E-Commerce",text:"Online stores that scale with you."},{icon:Link2,title:"Integrations",text:"Connect your tools. Streamline your workflow."},{icon:Settings,title:"Automation",text:"Work less. Do more."},{icon:Users,title:"Memberships",text:"Communities, courses, client portals."},{icon:Shield,title:"Ongoing Support",text:"Keep your site fast, secure, and growing."}];
const steps=["Discovery","Design","Build","Launch","Support"];
function Brand({variant="wide",className=""}:{variant?:"wide"|"stacked"|"mark",className?:string}){const src=variant==="wide"?"/assets/forged-logo-wide.webp":variant==="stacked"?"/assets/forged-logo-stacked.webp":"/assets/forged-logo-mark.webp";return <span className={`brand-asset brand-${variant} ${className}`.trim()}><img src={src} alt={variant==="mark"?"Forged Digital mark":"Forged Digital"}/></span>}
function HeroVideo(){return <video className="hero-video" autoPlay muted loop playsInline preload="metadata" poster="/assets/forged-hero-poster.webp" aria-hidden="true"><source src="/assets/forged-hero.webm" type="video/webm"/><source src="/assets/forged-hero.mp4" type="video/mp4"/></video>}
export default function Home(){const [mouse,setMouse]=useState({x:70,y:32});useEffect(()=>{const f=(e:MouseEvent)=>setMouse({x:e.clientX/window.innerWidth*100,y:e.clientY/window.innerHeight*100});window.addEventListener("mousemove",f);return()=>window.removeEventListener("mousemove",f)},[]);return <main style={{"--mx":`${mouse.x}%`,"--my":`${mouse.y}%`} as React.CSSProperties}>
<section className="desktop-build" id="top"><header className="desktop-header shell"><a className="desktop-logo official-logo" href="#top"><Brand variant="wide"/></a><nav><a href="#work">WORK</a><a href="#services">SERVICES</a><a href="#process">PROCESS</a><a href="#contact">CONTACT</a><a href="/portal">CLIENT LOGIN</a></nav><a className="d-outline" href="/contact">START A PROJECT <ArrowRight size={14}/></a></header>
<section className="d-hero"><HeroVideo/><div className="hero-video-shade"/><div className="ambient-light"/><div className="hero-smoke smoke-a"/><div className="hero-smoke smoke-b"/><div className="shell d-hero-grid"><div className="d-copy"><p>› FORGED DIGITAL</p><h1>WEBSITES BUILT<br/>TO <em>HIT DIFFERENT.</em></h1><span>Custom web design, e-commerce, integrations, and digital systems<br/>built around your business — not a template.</span><div><a className="d-red" href="/contact">START A PROJECT <ArrowRight size={14}/></a><a className="d-dark" href="#services">SEE WHAT WE BUILD</a></div></div><div className="forged-scene"><div className="embers">{Array.from({length:24}).map((_,i)=><i key={i} style={{left:`${(i*31)%96}%`,top:`${12+(i*23)%76}%`,animationDelay:`${i*.11}s`}}/>)}</div><div className="metal-f">F<span className="glow-cut g1"/><span className="glow-cut g2"/><span className="glow-cut g3"/></div><div className="rocks"><i/><i/><i/><i/><i/></div></div></div></section>
<section className="d-disc"><div className="shell">{["DESIGN.","DEVELOPMENT.","COMMERCE.","AUTOMATION."].map(x=><b key={x}>{x}<span>＋</span></b>)}</div></section>
<section id="services" className="d-section"><div className="shell d-cap"><div className="d-title"><p>CAPABILITIES</p><h2>MORE THAN WEBSITES.<br/>WE BUILD <em>DIGITAL<br/>INFRASTRUCTURE.</em></h2><span>From high-performing websites to full business systems,<br/>we help you grow, automate, and operate stronger online.</span></div><div className="d-services">{services.map(({icon:Icon,title,text})=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section id="work" className="d-section d-work"><div className="shell d-project"><div className="d-title"><p>FEATURED WORK</p><h2>REAL BUSINESSES.<br/>REAL RESULTS.</h2><span>Custom solutions for brands that are<br/>building what’s next.</span></div><div className="real-devices"><div className="mac"><div className="khs-screen khs-desktop"/></div><div className="iphone"><div className="khs-screen khs-mobile"/></div></div><div className="d-project-copy"><h3>KHS</h3><small>E-COMMERCE / COMMUNITY / CUSTOM DEVELOPMENT</small><p>A custom commerce and community platform built around a distinct local brand.</p><a href="https://keephuntsvillestrange.com" target="_blank" rel="noreferrer">VIEW PROJECT <ArrowRight size={14}/></a></div></div></section>
<section id="process" className="d-section d-process"><div className="process-rock"/><div className="shell"><div className="d-process-head"><div className="d-title"><p>OUR PROCESS</p><h2>A CLEAR PATH<br/>FROM IDEA TO IMPACT.</h2></div><span>No guesswork. No fluff. A clear process from concept to completion.</span></div><div className="d-timeline">{steps.map((s,i)=><article key={s}><b>0{i+1}</b><i/><h3>{s}</h3><p>{["Understand your goals, brand, and audience.","Turn ideas into a strategic visual plan.","Develop, integrate, test, and refine.","Optimize and go live with confidence.","Ongoing help to keep you growing."][i]}</p></article>)}</div></div></section>
<footer id="contact" className="d-footer shell"><a className="desktop-logo footer-logo official-logo" href="#top"><Brand variant="wide"/></a><div><a href="/portal">CLIENT LOGIN</a><a href="mailto:Aaron.forgeddigital@gmail.com">Aaron.forgeddigital@gmail.com</a><a href="tel:+18503901669">850-390-1669</a></div></footer></section>
<section className="mobile-build"><header className="mobile-header"><a className="mobile-brand official-logo" href="#top"><Brand variant="wide"/></a><div className="mobile-header-actions"><a href="/portal">CLIENT LOGIN</a><a href="/contact">START A PROJECT</a></div></header><section className="mobile-hero"><HeroVideo/><div className="hero-video-shade"/><div className="mobile-hero-content"><p>FORGED DIGITAL</p><h1>WEBSITES BUILT<br/>TO <em>HIT DIFFERENT.</em></h1><span>Custom web design, e-commerce, integrations, and digital systems built around your business — not a template.</span><div><a className="m-red" href="/contact">START A PROJECT <ArrowRight size={15}/></a><a className="m-dark" href="#services">SEE WHAT WE BUILD</a></div></div></section><section className="mobile-disciplines">{["DESIGN.","DEVELOPMENT.","COMMERCE.","AUTOMATION."].map(x=><b key={x}>{x}</b>)}</section><section className="mobile-section"><p className="m-label">CAPABILITIES</p><h2>MORE THAN WEBSITES.<br/>WE BUILD <em>DIGITAL INFRASTRUCTURE.</em></h2><div className="mobile-services">{services.map(({icon:Icon,title,text})=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="mobile-section mobile-work"><p className="m-label">FEATURED WORK</p><h2>REAL BUSINESSES.<br/>REAL RESULTS.</h2><div className="mobile-device-card"><div className="mobile-khs-preview khs-screen khs-mobile"/><strong>KHS</strong><span>E-COMMERCE / COMMUNITY / DEVELOPMENT</span><p>A custom commerce and community platform built around a distinct local brand.</p><a href="https://keephuntsvillestrange.com" target="_blank" rel="noreferrer">VIEW PROJECT <ArrowRight size={14}/></a></div></section><section className="mobile-section mobile-process"><p className="m-label">OUR PROCESS</p><h2>A CLEAR PATH<br/>FROM IDEA TO IMPACT.</h2><div>{steps.map((s,i)=><article key={s}><b>0{i+1}</b><span/><h3>{s}</h3></article>)}</div></section><footer className="mobile-footer"><Brand variant="stacked"/><a href="/portal">CLIENT LOGIN</a><a href="mailto:Aaron.forgeddigital@gmail.com">Aaron.forgeddigital@gmail.com</a><a href="tel:+18503901669">850-390-1669</a></footer></section></main>}
