"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Bell, Check, Circle, Clock3, Copy, LogOut, MessageSquare, Send, UserPlus, X } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { dispatchMessagePush } from "@/lib/push-notifications";
import { PushNotificationControl } from "@/components/push-notification-control";
import "./admin.css";
import "./admin-chat-ui.css";
import "./admin-login.css";

type Row=any;

export default function AdminPage(){
  const [loading,setLoading]=useState(true);
  const [user,setUser]=useState<any>(null);
  const [profile,setProfile]=useState<Row>(null);
  const [clients,setClients]=useState<Row[]>([]);
  const [selected,setSelected]=useState<Row>(null);
  const [project,setProject]=useState<Row>(null);
  const [milestones,setMilestones]=useState<Row[]>([]);
  const [assets,setAssets]=useState<Row[]>([]);
  const [messages,setMessages]=useState<Row[]>([]);
  const [threadMessages,setThreadMessages]=useState<Row[]>([]);
  const [contacts,setContacts]=useState<Row[]>([]);
  const [invitations,setInvitations]=useState<Row[]>([]);
  const [invite,setInvite]=useState({contact_name:"",company_name:"",email:""});
  const [chat,setChat]=useState("");
  const [notice,setNotice]=useState("");
  const [chatDrawer,setChatDrawer]=useState(false);
  const [chatView,setChatView]=useState(false);
  const [adminAuth,setAdminAuth]=useState({email:"",password:""});
  const [authNotice,setAuthNotice]=useState("");
  const [authBusy,setAuthBusy]=useState(false);

  useEffect(()=>{supabase.auth.getSession().then(async({data})=>{const u=data.session?.user;if(!u){setLoading(false);return;}setUser(u);const {data:p}=await supabase.from("profiles").select("*").eq("id",u.id).single();setProfile(p);if(p?.role!=="admin"){setLoading(false);return;}const [{data:c},{data:ct},{data:iv},{data:tm}]=await Promise.all([supabase.from("client_accounts").select("*").order("created_at",{ascending:false}),supabase.from("contact_submissions").select("*").order("created_at",{ascending:false}).limit(100),supabase.from("client_invitations").select("*").order("created_at",{ascending:false}).limit(50),supabase.from("messages").select("*").order("created_at",{ascending:false})]);setClients(c||[]);setContacts(ct||[]);setInvitations(iv||[]);setThreadMessages(tm||[]);const first=(c||[])[0];if(first)await chooseClient(first);setLoading(false);});},[]);
  useEffect(()=>{if(!user)return;const ch=supabase.channel("admin-all-messages").on("postgres_changes",{event:"INSERT",schema:"public",table:"messages"},payload=>{const row=payload.new;setThreadMessages(cur=>cur.some(x=>x.id===row.id)?cur:[row,...cur]);if(selected?.id===row.client_id)setMessages(cur=>cur.some(x=>x.id===row.id)?cur:[...cur,row])}).subscribe();return()=>{supabase.removeChannel(ch)}},[user?.id,selected?.id]);

  async function chooseClient(c:Row){setSelected(c);setNotice("");const [{data:p},{data:a},{data:m}]=await Promise.all([supabase.from("projects").select("*").eq("client_id",c.id).order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("branding_assets").select("*").eq("client_id",c.id).order("created_at",{ascending:false}),supabase.from("messages").select("*").eq("client_id",c.id).order("created_at",{ascending:true})]);setProject(p||null);setAssets(a||[]);setMessages(m||[]);if(p){const {data:ms}=await supabase.from("project_milestones").select("*").eq("project_id",p.id).order("position");setMilestones(ms||[])}else setMilestones([])}
  async function openChat(c:Row){await chooseClient(c);setChatDrawer(false);setChatView(true);if(user){const readAt=new Date().toISOString();await supabase.from("messages").update({read_at:readAt}).eq("client_id",c.id).neq("sender_id",user.id).is("read_at",null);setThreadMessages(cur=>cur.map(m=>m.client_id===c.id&&m.sender_id!==user.id&&!m.read_at?{...m,read_at:readAt}:m))}}
  async function createInvite(e:React.FormEvent){e.preventDefault();if(!user||!invite.email.trim())return;const {data,error}=await supabase.from("client_invitations").insert({email:invite.email.trim().toLowerCase(),contact_name:invite.contact_name.trim()||null,company_name:invite.company_name.trim()||null,created_by:user.id}).select().single();if(error){setNotice(error.message);return;}setInvitations(cur=>[data,...cur]);setInvite({contact_name:"",company_name:"",email:""});setNotice("Client invitation created.");}
  function inviteUrl(row:Row){return `${window.location.origin}/portal?invite=${row.token}`}
  async function copyInvite(row:Row){await navigator.clipboard.writeText(inviteUrl(row));setNotice("Invite link copied.")}
  async function revokeInvite(row:Row){const {error}=await supabase.from("client_invitations").update({status:"revoked"}).eq("id",row.id);if(error){setNotice(error.message);return;}setInvitations(cur=>cur.map(x=>x.id===row.id?{...x,status:"revoked"}:x));setNotice("Invitation revoked.")}
  async function saveProject(){if(!project)return;const {error}=await supabase.from("projects").update({status:project.status,progress:Number(project.progress)||0,target_launch:project.target_launch||null}).eq("id",project.id);setNotice(error?error.message:"Project progress saved.")}
  async function setMilestone(id:string,status:string){await supabase.from("project_milestones").update({status,completed_at:status==="done"?new Date().toISOString():null}).eq("id",id);setMilestones(cur=>cur.map(m=>m.id===id?{...m,status}:m));}
  async function send(){if(!chat.trim()||!selected||!user)return;const body=chat.trim();setChat("");const {data,error}=await supabase.from("messages").insert({client_id:selected.id,sender_id:user.id,body}).select().single();if(error){setNotice(error.message);setChat(body);return;}if(data){setMessages(cur=>cur.some(x=>x.id===data.id)?cur:[...cur,data]);void dispatchMessagePush(data.id)}}
  async function markContact(id:string,status:string){await supabase.from("contact_submissions").update({status}).eq("id",id);setContacts(cur=>cur.map(c=>c.id===id?{...c,status}:c))}
  async function signOut(){await supabase.auth.signOut();window.location.href="/portal"}
  async function adminSignIn(e:React.FormEvent){e.preventDefault();setAuthBusy(true);setAuthNotice("");await supabase.auth.signOut();const {data,error}=await supabase.auth.signInWithPassword({email:adminAuth.email.trim(),password:adminAuth.password});if(error){setAuthNotice(error.message);setAuthBusy(false);return;}const {data:adminProfile}=await supabase.from("profiles").select("role").eq("id",data.user.id).single();if(adminProfile?.role!=="admin"){await supabase.auth.signOut();setAuthNotice("This account does not have administrator access.");setAuthBusy(false);return;}window.location.reload()}

  if(loading)return <main className="admin-gate"><p>LOADING...</p></main>;
  if(!user||profile?.role!=="admin")return <main className="admin-gate admin-login-gate"><div className="admin-login-card"><img src="/assets/forged-logo-stacked.webp" alt="Forged Digital"/><p className="eyebrow">FORGED DIGITAL</p><h1>ADMIN SIGN IN</h1>{user&&profile?.role!=="admin"&&<span className="admin-current-session">A client account is currently signed in. Admin login will switch accounts.</span>}<form onSubmit={adminSignIn}><input required type="email" autoComplete="username" placeholder="Admin email" value={adminAuth.email} onChange={e=>setAdminAuth({...adminAuth,email:e.target.value})}/><input required type="password" autoComplete="current-password" placeholder="Password" value={adminAuth.password} onChange={e=>setAdminAuth({...adminAuth,password:e.target.value})}/><button type="submit" disabled={authBusy}>{authBusy?"SIGNING IN...":"SIGN IN TO ADMIN"}</button></form>{authNotice&&<span className="admin-auth-notice">{authNotice}</span>}<Link href="/portal">RETURN TO CLIENT PORTAL</Link></div></main>;

  const threads=clients.map(client=>{const rows=threadMessages.filter(message=>message.client_id===client.id);return{client,last:rows[0],unread:rows.filter(message=>message.sender_id!==user.id&&!message.read_at).length}}).filter(thread=>thread.last).sort((a,b)=>new Date(b.last.created_at).getTime()-new Date(a.last.created_at).getTime());
  const unreadCount=threads.reduce((total,thread)=>total+thread.unread,0);

  return <main className="admin-page"><aside className="admin-sidebar"><Link href="/"><img src="/assets/forged-logo-stacked.webp" alt="Forged Digital"/></Link><p>ADMIN</p><h2>CLIENTS</h2><div className="admin-client-list">{clients.length===0?<span className="admin-empty">No clients yet.</span>:clients.map(c=><button key={c.id} className={selected?.id===c.id?"active":""} onClick={()=>{setChatView(false);chooseClient(c)}}><b>{c.company_name||c.contact_name||c.email||"Unnamed Client"}</b><span>{c.email}</span></button>)}</div><PushNotificationControl/><button className="admin-signout" onClick={signOut}><LogOut size={16}/> SIGN OUT</button></aside>{chatDrawer&&<><button className="admin-chat-backdrop" aria-label="Close conversations" onClick={()=>setChatDrawer(false)}/><aside className="admin-chat-drawer"><header><div><p>PRIVATE CHAT</p><h2>CONVERSATIONS</h2></div><button aria-label="Close conversations" onClick={()=>setChatDrawer(false)}><X/></button></header><div className="admin-thread-list">{threads.length===0?<span>No conversations yet.</span>:threads.map(thread=><button key={thread.client.id} onClick={()=>openChat(thread.client)}><div className="thread-avatar">{(thread.client.company_name||thread.client.contact_name||"C").slice(0,1).toUpperCase()}</div><div><b>{thread.client.company_name||thread.client.contact_name||thread.client.email}</b><span>{thread.last.body}</span><small>{new Date(thread.last.created_at).toLocaleString()}</small></div>{thread.unread>0&&<i>{thread.unread}</i>}</button>)}</div></aside></>}<section className="admin-main"><header><div><span>FORGED DIGITAL</span><b>{chatView?"Client Conversation":"Client Operations"}</b></div><div className="admin-header-actions"><button className="admin-chat-trigger" onClick={()=>setChatDrawer(true)}><Bell size={17}/><span>CHAT</span>{unreadCount>0&&<i>{unreadCount}</i>}</button><Link href="/portal">VIEW CLIENT PORTAL</Link></div></header><div className={`admin-content ${chatView?"admin-content-chat":""}`}>

{chatView&&selected?<section className="admin-chat-page"><button className="admin-chat-return" onClick={()=>setChatView(false)}><ArrowLeft size={15}/> BACK TO ADMIN OVERVIEW</button><div className="admin-chat-page-title"><div><p className="eyebrow">CLIENT CONVERSATION</p><h1>{selected.company_name||selected.contact_name||selected.email}</h1></div><span>{project?.status||"Discovery"} · {project?.progress||0}% COMPLETE</span></div><div className="admin-chat-layout"><aside className="admin-chat-client"><p className="eyebrow">CLIENT INFO</p><h2>{selected.contact_name||"Client"}</h2><dl><div><dt>COMPANY</dt><dd>{selected.company_name||"—"}</dd></div><div><dt>EMAIL</dt><dd>{selected.email||"—"}</dd></div><div><dt>PHONE</dt><dd>{selected.phone||"—"}</dd></div><div><dt>PROJECT</dt><dd>{project?.name||"Website Build"}</dd></div><div><dt>TARGET LAUNCH</dt><dd>{project?.target_launch||"Not scheduled"}</dd></div></dl><button onClick={()=>setChatView(false)}>VIEW FULL CLIENT WORKSPACE</button></aside><div className="admin-chat-panel"><div className="admin-chat admin-chat-expanded">{messages.length===0?<span className="admin-empty-chat">No messages yet. Start the conversation below.</span>:messages.map(m=><div key={m.id} className={m.sender_id===user.id?"mine":"theirs"}><small>{m.sender_id===user.id?"YOU":"CLIENT"} · {new Date(m.created_at).toLocaleString()}</small><p>{m.body}</p></div>)}</div><div className="admin-compose admin-compose-expanded"><textarea value={chat} onChange={e=>setChat(e.target.value)} placeholder="Message client..."/><button onClick={send}><Send size={16}/> SEND</button></div></div></div></section>:<>

<section><p className="eyebrow">CLIENT ACCESS</p><h1>CREATE / INVITE CLIENT</h1><form className="admin-invite-form" onSubmit={createInvite}><label><span>CONTACT NAME</span><input value={invite.contact_name} onChange={e=>setInvite({...invite,contact_name:e.target.value})} placeholder="Client name"/></label><label><span>COMPANY</span><input value={invite.company_name} onChange={e=>setInvite({...invite,company_name:e.target.value})} placeholder="Company name"/></label><label><span>EMAIL</span><input required type="email" value={invite.email} onChange={e=>setInvite({...invite,email:e.target.value})} placeholder="client@company.com"/></label><button type="submit"><UserPlus size={16}/> CREATE INVITE</button></form><div className="admin-invites">{invitations.slice(0,8).map(row=><article key={row.id}><div><b>{row.company_name||row.contact_name||row.email}</b><span>{row.email}</span><small>{row.status.toUpperCase()} · expires {new Date(row.expires_at).toLocaleDateString()}</small></div><div>{row.status==="pending"&&<button onClick={()=>copyInvite(row)}><Copy size={14}/> COPY LINK</button>}{row.status==="pending"&&<button className="revoke" onClick={()=>revokeInvite(row)}><X size={14}/> REVOKE</button>}</div></article>)}</div></section>

<section><p className="eyebrow">LEADS</p><h1>CONTACT INTAKE</h1><div className="admin-leads">{contacts.length===0?<p>No submissions yet.</p>:contacts.map(c=><article key={c.id}><div><b>{c.name}</b><span>{c.company_name||"No company"} · {c.email} · {c.phone||"No phone"}</span><small>{c.domain_or_website||"No website supplied"}</small></div><select value={c.status} onChange={e=>markContact(c.id,e.target.value)}><option value="new">New</option><option value="contacted">Contacted</option><option value="qualified">Qualified</option><option value="closed">Closed</option></select></article>)}</div></section>

{selected?<><section><p className="eyebrow">SELECTED CLIENT</p><h1>{selected.company_name||selected.contact_name||selected.email}</h1><div className="admin-project-grid"><label><span>STATUS</span><input value={project?.status||""} onChange={e=>setProject({...project,status:e.target.value})}/></label><label><span>PROGRESS %</span><input type="number" min="0" max="100" value={project?.progress??0} onChange={e=>setProject({...project,progress:e.target.value})}/></label><label><span>TARGET LAUNCH</span><input type="date" value={project?.target_launch||""} onChange={e=>setProject({...project,target_launch:e.target.value})}/></label><button onClick={saveProject}>SAVE PROJECT</button></div><div className="admin-milestones">{milestones.map(m=><article key={m.id}>{m.status==="done"?<Check/>:m.status==="active"?<Clock3/>:<Circle/>}<div><b>{m.title}</b><span>{m.description}</span></div><select value={m.status} onChange={e=>setMilestone(m.id,e.target.value)}><option value="pending">Pending</option><option value="active">In Progress</option><option value="done">Complete</option></select></article>)}</div></section><section className="admin-two"><div><p className="eyebrow">BRANDING</p><h2>CLIENT ASSETS</h2><div className="admin-assets">{assets.length===0?<p>No assets uploaded.</p>:assets.map(a=><article key={a.id}><b>{a.file_name}</b><span>{a.asset_type} · {a.mime_type||"file"}</span></article>)}</div></div><div><p className="eyebrow">PRIVATE CHAT</p><h2>MESSAGES</h2><button className="admin-open-chat" onClick={()=>openChat(selected)}><MessageSquare size={16}/> OPEN CLIENT CHAT</button><div className="admin-chat">{messages.map(m=><div key={m.id} className={m.sender_id===user.id?"mine":"theirs"}><small>{m.sender_id===user.id?"YOU":"CLIENT"}</small><p>{m.body}</p></div>)}</div><div className="admin-compose"><textarea value={chat} onChange={e=>setChat(e.target.value)} placeholder="Message client..."/><button onClick={send}><Send size={16}/> SEND</button></div></div></section></>:<section className="admin-no-client"><p className="eyebrow">CLIENT WORKSPACE</p><h1>NO CLIENT SELECTED</h1><p>Create an invitation above. Once the client accepts it and creates their account, their project workspace will appear here automatically.</p></section>}{notice&&<div className="admin-notice">{notice}</div>}</>}</div></section></main>
}
