"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowRight,CheckSquare,CircleDollarSign,FileText,FolderKanban,Inbox,MessageSquare,Users} from "lucide-react";
import {supabase} from "@/lib/supabase";
import "./dashboard.css";
type Row=any;
const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format((c||0)/100);
export default function AdminDashboard(){
 const [loading,setLoading]=useState(true),[authorized,setAuthorized]=useState(false),[user,setUser]=useState<any>(null),[clients,setClients]=useState<Row[]>([]),[leads,setLeads]=useState<Row[]>([]),[proposals,setProposals]=useState<Row[]>([]),[invoices,setInvoices]=useState<Row[]>([]),[projects,setProjects]=useState<Row[]>([]),[approvals,setApprovals]=useState<Row[]>([]),[tasks,setTasks]=useState<Row[]>([]),[messages,setMessages]=useState<Row[]>([]);
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session?.user){setLoading(false);return}setUser(session.user);const {data:p}=await supabase.from("profiles").select("role").eq("id",session.user.id).single();if(p?.role!=="admin"){setLoading(false);return}setAuthorized(true);const [{data:c},{data:l},{data:pr},{data:i},{data:pj},{data:a},{data:t},{data:m}]=await Promise.all([supabase.from("client_accounts").select("id,company_name,contact_name,email,created_at"),supabase.from("contact_submissions").select("*").order("created_at",{ascending:false}),supabase.from("proposals").select("*").order("updated_at",{ascending:false}),supabase.from("invoices").select("*").order("updated_at",{ascending:false}),supabase.from("projects").select("*").order("updated_at",{ascending:false}),supabase.from("client_approvals").select("*").order("requested_at",{ascending:false}),supabase.from("client_tasks").select("*").order("updated_at",{ascending:false}),supabase.from("messages").select("*").order("created_at",{ascending:false}).limit(100)]);setClients(c||[]);setLeads(l||[]);setProposals(pr||[]);setInvoices(i||[]);setProjects(pj||[]);setApprovals(a||[]);setTasks(t||[]);setMessages(m||[]);setLoading(false)})()},[]);
 const clientName=(id:string)=>{const c=clients.find(x=>x.id===id);return c?.company_name||c?.contact_name||c?.email||"Client"};
 const openProposals=proposals.filter(p=>["draft","sent","changes_requested"].includes(p.status));
 const outstanding=invoices.filter(i=>!["paid","void","draft"].includes(i.status));
 const outstandingCents=outstanding.reduce((n,i)=>n+Math.max(0,(i.total_cents||0)-(i.amount_paid_cents||0)),0);
 const activeProjects=projects.filter(p=>!(["complete","completed","closed","archived"].includes(String(p.status||"").toLowerCase())));
 const pendingApprovals=approvals.filter(a=>a.status==="pending");
 const overdueTasks=tasks.filter(t=>t.status!=="done"&&t.status!=="complete"&&t.due_date&&new Date(t.due_date+"T23:59:59")<new Date());
 const unread=messages.filter(m=>m.sender_id!==user?.id&&!m.read_at);
 const newLeads=leads.filter(l=>l.status==="new");
 const activity=useMemo(()=>{const rows:any[]=[];leads.slice(0,8).forEach(x=>rows.push({at:x.created_at,label:"New inquiry",detail:`${x.name}${x.company_name?` · ${x.company_name}`:""}`,href:"/admin/leads"}));proposals.slice(0,8).forEach(x=>rows.push({at:x.updated_at||x.created_at,label:`Proposal ${String(x.status||"").replaceAll("_"," ")}`,detail:`${x.proposal_number} · ${clientName(x.client_id)}`,href:"/admin/proposals"}));invoices.slice(0,8).forEach(x=>rows.push({at:x.updated_at||x.created_at,label:`Invoice ${x.status}`,detail:`${x.invoice_number} · ${clientName(x.client_id)}`,href:"/admin/billing"}));approvals.slice(0,8).forEach(x=>rows.push({at:x.responded_at||x.requested_at,label:`Approval ${x.status}`,detail:`${x.title} · ${clientName(x.client_id)}`,href:"/admin/workflow"}));messages.slice(0,8).forEach(x=>rows.push({at:x.created_at,label:x.sender_id===user?.id?"Message sent":"Client message",detail:`${clientName(x.client_id)} · ${String(x.body||"").slice(0,70)}`,href:"/admin"}));return rows.filter(x=>x.at).sort((a,b)=>+new Date(b.at)-+new Date(a.at)).slice(0,14)},[leads,proposals,invoices,approvals,messages,clients,user?.id]);
 if(loading)return <main className="fd-dash-gate">LOADING COMMAND CENTER...</main>;
 if(!authorized)return <main className="fd-dash-gate"><h1>ADMIN ACCESS REQUIRED</h1><Link href="/admin">ADMIN SIGN IN</Link></main>;
 const cards=[{label:"NEW LEADS",value:newLeads.length,sub:`${leads.length} total inquiries`,href:"/admin/leads",Icon:Inbox},{label:"ACTIVE CLIENTS",value:clients.length,sub:`${activeProjects.length} active projects`,href:"/admin",Icon:Users},{label:"OPEN PROPOSALS",value:openProposals.length,sub:money(openProposals.reduce((n,p)=>n+(p.total_cents||0),0)),href:"/admin/proposals",Icon:FileText},{label:"OUTSTANDING",value:money(outstandingCents),sub:`${outstanding.length} open invoices`,href:"/admin/billing",Icon:CircleDollarSign},{label:"ACTIVE PROJECTS",value:activeProjects.length,sub:`${projects.length} total projects`,href:"/admin",Icon:FolderKanban},{label:"PENDING APPROVALS",value:pendingApprovals.length,sub:`${overdueTasks.length} overdue tasks`,href:"/admin/workflow",Icon:CheckSquare},{label:"UNREAD MESSAGES",value:unread.length,sub:`${messages.length} recent messages`,href:"/admin",Icon:MessageSquare}];
 return <main className="fd-dashboard"><header><div><p>FORGED DIGITAL</p><h1>COMMAND CENTER</h1><span>Sales, billing, projects and client activity at a glance.</span></div><div><Link href="/admin">CLIENT OPERATIONS</Link><Link href="/">VIEW WEBSITE</Link></div></header><section className="fd-stat-grid">{cards.map(({label,value,sub,href,Icon})=><Link href={href} className="fd-stat" key={label}><div><Icon size={19}/><span>{label}</span></div><strong>{value}</strong><small>{sub}</small><i><ArrowRight size={14}/></i></Link>)}</section><section className="fd-dashboard-grid"><article><div className="fd-panel-head"><div><p>RECENT ACTIVITY</p><h2>BUSINESS FEED</h2></div></div><div className="fd-feed">{activity.length===0?<span className="fd-empty">No activity yet.</span>:activity.map((x,i)=><Link href={x.href} key={`${x.at}-${i}`}><i/><div><b>{x.label}</b><span>{x.detail}</span><small>{new Date(x.at).toLocaleString()}</small></div><ArrowRight size={14}/></Link>)}</div></article><aside><div className="fd-panel-head"><div><p>NEEDS ATTENTION</p><h2>QUEUE</h2></div></div><Link href="/admin/leads"><b>{newLeads.length}</b><span>New leads waiting</span></Link><Link href="/admin/proposals"><b>{openProposals.filter(p=>p.status==="changes_requested").length}</b><span>Proposal change requests</span></Link><Link href="/admin/billing"><b>{outstanding.filter(i=>i.due_date&&new Date(i.due_date+"T23:59:59")<new Date()).length}</b><span>Overdue invoices</span></Link><Link href="/admin/workflow"><b>{pendingApprovals.length}</b><span>Pending approvals</span></Link><Link href="/admin/workflow"><b>{overdueTasks.length}</b><span>Overdue action items</span></Link><Link href="/admin"><b>{unread.length}</b><span>Unread client messages</span></Link></aside></section></main>
}