"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,CheckCircle2,MessageSquareText,XCircle} from "lucide-react";
import {supabase} from "@/lib/supabase";
import "./proposals.css";
type Row=any; const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format((c||0)/100);
export default function ClientProposals(){
 const [loading,setLoading]=useState(true),[allowed,setAllowed]=useState(false),[proposals,setProposals]=useState<Row[]>([]),[selected,setSelected]=useState<Row|null>(null),[note,setNote]=useState(""),[notice,setNotice]=useState("");
 async function load(){const {data:{session}}=await supabase.auth.getSession();if(!session){setLoading(false);return;}const {data:p}=await supabase.from("profiles").select("role").eq("id",session.user.id).single();if(p?.role==="admin"){window.location.href="/admin/proposals";return;}setAllowed(true);const {data}=await supabase.from("proposals").select("*,proposal_items(*)").order("created_at",{ascending:false});const rows=(data||[]).map((p:any)=>({...p,proposal_items:(p.proposal_items||[]).sort((a:any,b:any)=>a.position-b.position)}));setProposals(rows);setSelected(rows[0]||null);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function respond(decision:"accepted"|"changes_requested"|"declined"){if(!selected)return;setNotice("Submitting response...");const {error}=await supabase.rpc("respond_to_proposal",{target_proposal:selected.id,decision,response_note:note||null});if(error){setNotice(error.message);return;}setNotice(decision==="accepted"?"Proposal accepted. Forged Digital has been notified.":decision==="changes_requested"?"Change request sent to Forged Digital.":"Proposal declined.");setNote("");await load()}
 if(loading)return <main className="client-proposal-gate">LOADING PROPOSALS...</main>;
 if(!allowed)return <main className="client-proposal-gate"><h1>CLIENT SIGN IN REQUIRED</h1><Link href="/portal">SIGN IN</Link></main>;
 return <main className="client-proposal-page"><header><Link href="/portal"><ArrowLeft size={16}/> BACK TO PORTAL</Link><img src="/assets/forged-logo-wide.webp" alt="Forged Digital"/><span>PROPOSALS</span></header><div className="client-proposal-shell">
 <aside><p className="eyebrow">YOUR PROPOSALS</p>{proposals.length===0?<div className="empty">No proposals are waiting for you.</div>:proposals.map(p=><button key={p.id} onClick={()=>{setSelected(p);setNote("");setNotice("")}} className={selected?.id===p.id?"active":""}><b>{p.proposal_number}</b><span>{p.title}</span><small>{p.status.replaceAll("_"," ").toUpperCase()} · {money(p.total_cents)}</small></button>)}</aside>
 <section>{!selected?<div className="proposal-empty"><h1>NO PROPOSAL SELECTED</h1></div>:<><div className="proposal-head"><div><p className="eyebrow">FORGED DIGITAL PROPOSAL</p><h1>{selected.title}</h1><span>{selected.proposal_number}{selected.valid_until?` · Valid through ${new Date(selected.valid_until+"T00:00:00").toLocaleDateString()}`:""}</span></div><strong>{money(selected.total_cents)}</strong></div><div className="proposal-status">STATUS: <b>{selected.status.replaceAll("_"," ").toUpperCase()}</b></div><div className="proposal-lines"><div className="line header"><span>DESCRIPTION</span><span>QTY</span><span>RATE</span><span>AMOUNT</span></div>{selected.proposal_items?.map((i:any)=><div className="line" key={i.id}><span>{i.description}</span><span>{Number(i.quantity)}</span><span>{money(i.unit_amount_cents)}</span><b>{money(Math.round(Number(i.quantity)*i.unit_amount_cents))}</b></div>)}</div><div className="proposal-summary"><div>{selected.notes&&<><h3>SCOPE / NOTES</h3><p>{selected.notes}</p></>}{selected.terms&&<><h3>TERMS</h3><p>{selected.terms}</p></>}</div><aside><p><span>SUBTOTAL</span><b>{money(selected.subtotal_cents)}</b></p><p><span>TAX</span><b>{money(selected.tax_cents)}</b></p><p><span>DISCOUNT</span><b>-{money(selected.discount_cents)}</b></p>{selected.deposit_cents>0&&<p><span>DEPOSIT</span><b>{money(selected.deposit_cents)}</b></p>}<p className="total"><span>TOTAL</span><strong>{money(selected.total_cents)}</strong></p></aside></div>{selected.response_notes&&<div className="existing-response"><b>YOUR LAST NOTE</b><p>{selected.response_notes}</p></div>}{["sent","changes_requested"].includes(selected.status)&&<div className="proposal-response"><label><span>OPTIONAL NOTE / CHANGE REQUEST</span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add any questions or requested changes here..."/></label><div><button className="accept" onClick={()=>respond("accepted")}><CheckCircle2 size={16}/> ACCEPT PROPOSAL</button><button onClick={()=>respond("changes_requested")}><MessageSquareText size={16}/> REQUEST CHANGES</button><button className="decline" onClick={()=>respond("declined")}><XCircle size={16}/> DECLINE</button></div></div>}{selected.status==="accepted"&&<div className="accepted-banner"><CheckCircle2 size={20}/> PROPOSAL ACCEPTED — FORGED DIGITAL HAS BEEN NOTIFIED</div>}{notice&&<div className="proposal-notice">{notice}</div>}</>}</section>
 </div></main>;
}
