"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Plus, Trash2, Send, DollarSign } from "lucide-react";
import { supabase } from "@/lib/supabase";
import "./billing.css";

type Row=any;
type Item={description:string;quantity:number;unit_amount:string};
const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format((c||0)/100);

export default function AdminBillingPage(){
  const [loading,setLoading]=useState(true),[allowed,setAllowed]=useState(false),[clients,setClients]=useState<Row[]>([]),[invoices,setInvoices]=useState<Row[]>([]),[notice,setNotice]=useState("");
  const [clientId,setClientId]=useState(""),[dueDate,setDueDate]=useState(""),[taxRate,setTaxRate]=useState("0"),[discount,setDiscount]=useState("0"),[notes,setNotes]=useState(""),[terms,setTerms]=useState("Due upon receipt unless otherwise stated."),[items,setItems]=useState<Item[]>([{description:"Custom website development",quantity:1,unit_amount:"0.00"}]);
  const subtotal=useMemo(()=>items.reduce((s,i)=>s+Math.round((Number(i.unit_amount)||0)*100*(Number(i.quantity)||0)),0),[items]);
  const tax=Math.round(subtotal*(Number(taxRate)||0)/100),discountCents=Math.round((Number(discount)||0)*100),total=Math.max(0,subtotal+tax-discountCents);

  async function load(){const {data:{session}}=await supabase.auth.getSession();if(!session){setLoading(false);return;}const {data:p}=await supabase.from("profiles").select("role").eq("id",session.user.id).single();if(p?.role!=="admin"){setLoading(false);return;}setAllowed(true);const [{data:c},{data:i}]=await Promise.all([supabase.from("client_accounts").select("*").order("company_name"),supabase.from("invoices").select("*,client_accounts(company_name,contact_name,email)").order("created_at",{ascending:false})]);setClients(c||[]);setInvoices(i||[]);if(c?.[0])setClientId(c[0].id);setLoading(false)}
  useEffect(()=>{load()},[]);
  function changeItem(idx:number,key:keyof Item,value:string|number){setItems(cur=>cur.map((i,n)=>n===idx?{...i,[key]:value}:i))}
  async function createInvoice(){if(!clientId||!items.some(i=>i.description.trim()&&Number(i.unit_amount)>0)){setNotice("Choose a client and add at least one billable line item.");return;}setNotice("Creating invoice...");const {data:{user}}=await supabase.auth.getUser();const {data:inv,error}=await supabase.from("invoices").insert({client_id:clientId,due_date:dueDate||null,tax_rate:Number(taxRate)||0,discount_cents:discountCents,notes:notes||null,terms:terms||null,created_by:user?.id||null}).select().single();if(error||!inv){setNotice(error?.message||"Could not create invoice.");return;}const rows=items.filter(i=>i.description.trim()).map((i,n)=>({invoice_id:inv.id,position:n,description:i.description.trim(),quantity:Number(i.quantity)||1,unit_amount_cents:Math.round((Number(i.unit_amount)||0)*100)}));const {error:itemError}=await supabase.from("invoice_items").insert(rows);if(itemError){setNotice(itemError.message);return;}await supabase.rpc("recalculate_invoice_totals",{target_invoice:inv.id});setNotice(`Invoice ${inv.invoice_number} created.`);setItems([{description:"Custom website development",quantity:1,unit_amount:"0.00"}]);setDiscount("0");setTaxRate("0");setNotes("");setDueDate("");await load();}
  async function markSent(inv:Row){const {error}=await supabase.from("invoices").update({status:"sent",sent_at:new Date().toISOString()}).eq("id",inv.id);setNotice(error?error.message:`${inv.invoice_number} marked sent.`);if(!error)await load()}
  async function recordPayment(inv:Row){const value=window.prompt(`Record payment for ${inv.invoice_number}. Amount in dollars:`);if(!value)return;const cents=Math.round(Number(value)*100);if(!Number.isFinite(cents)||cents<=0){setNotice("Enter a valid payment amount.");return;}const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from("invoice_payments").insert({invoice_id:inv.id,amount_cents:cents,provider:"manual",status:"completed",paid_at:new Date().toISOString(),recorded_by:user?.id||null});setNotice(error?error.message:"Payment recorded.");if(!error)await load()}

  if(loading)return <main className="billing-gate">LOADING BILLING...</main>;
  if(!allowed)return <main className="billing-gate"><h1>ADMIN ACCESS REQUIRED</h1><Link href="/portal">CLIENT LOGIN</Link></main>;
  return <main className="billing-page"><header><Link href="/admin"><ArrowLeft size={16}/> BACK TO ADMIN</Link><img src="/assets/forged-logo-wide.webp" alt="Forged Digital"/><span>BILLING & INVOICES</span></header><div className="billing-shell">
    <section className="invoice-builder"><p className="eyebrow">ADMIN BILLING</p><h1>CREATE INVOICE</h1><div className="billing-grid"><label><span>CLIENT</span><select value={clientId} onChange={e=>setClientId(e.target.value)}>{clients.map(c=><option key={c.id} value={c.id}>{c.company_name||c.contact_name||c.email}</option>)}</select></label><label><span>DUE DATE</span><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><label><span>TAX %</span><input type="number" min="0" step="0.01" value={taxRate} onChange={e=>setTaxRate(e.target.value)}/></label><label><span>DISCOUNT $</span><input type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)}/></label></div>
    <div className="line-items"><div className="line-head"><span>DESCRIPTION</span><span>QTY</span><span>RATE</span><span></span></div>{items.map((i,n)=><div className="line-row" key={n}><input value={i.description} onChange={e=>changeItem(n,"description",e.target.value)}/><input type="number" min="0.01" step="0.01" value={i.quantity} onChange={e=>changeItem(n,"quantity",e.target.value)}/><input type="number" min="0" step="0.01" value={i.unit_amount} onChange={e=>changeItem(n,"unit_amount",e.target.value)}/><button onClick={()=>setItems(cur=>cur.filter((_,x)=>x!==n))} disabled={items.length===1}><Trash2 size={15}/></button></div>)}<button className="add-line" onClick={()=>setItems(cur=>[...cur,{description:"",quantity:1,unit_amount:"0.00"}])}><Plus size={15}/> ADD LINE ITEM</button></div>
    <div className="invoice-bottom"><div><label><span>NOTES</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Project or payment notes..."/></label><label><span>TERMS</span><textarea value={terms} onChange={e=>setTerms(e.target.value)}/></label></div><aside><p><span>SUBTOTAL</span><b>{money(subtotal)}</b></p><p><span>TAX</span><b>{money(tax)}</b></p><p><span>DISCOUNT</span><b>-{money(discountCents)}</b></p><p className="grand"><span>TOTAL</span><strong>{money(total)}</strong></p><button onClick={createInvoice}>CREATE INVOICE</button></aside></div>{notice&&<div className="billing-notice">{notice}</div>}</section>
    <section><p className="eyebrow">HISTORY</p><h1>INVOICES</h1><div className="invoice-list">{invoices.length===0?<p className="empty">No invoices yet.</p>:invoices.map(inv=><article key={inv.id}><div><b>{inv.invoice_number}</b><span>{inv.client_accounts?.company_name||inv.client_accounts?.contact_name||inv.client_accounts?.email}</span><small>{inv.status.toUpperCase()} · issued {new Date(inv.issue_date).toLocaleDateString()}{inv.due_date?` · due ${new Date(inv.due_date+"T00:00:00").toLocaleDateString()}`:""}</small></div><div className="invoice-amount"><strong>{money(inv.total_cents)}</strong><span>{money(Math.max(0,inv.total_cents-inv.amount_paid_cents))} due</span></div><div className="invoice-actions">{inv.status==="draft"&&<button onClick={()=>markSent(inv)}><Send size={14}/> MARK SENT</button>}{inv.status!=="paid"&&inv.status!=="void"&&<button onClick={()=>recordPayment(inv)}><DollarSign size={14}/> RECORD PAYMENT</button>}</div></article>)}</div></section>
  </div></main>;
}
