"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { FileText, Upload, CheckCircle2, ListTodo, Download, Bell, ArrowLeft } from "lucide-react";
import { supabase } from "@/lib/supabase";
import "./workflow.css";

type Row=any;
export default function AdminWorkflowPage(){
 const [loading,setLoading]=useState(true),[user,setUser]=useState<any>(null),[profile,setProfile]=useState<Row>(null),[clients,setClients]=useState<Row[]>([]),[selected,setSelected]=useState<Row>(null),[docs,setDocs]=useState<Row[]>([]),[approvals,setApprovals]=useState<Row[]>([]),[tasks,setTasks]=useState<Row[]>([]),[notice,setNotice]=useState("");
 const [docForm,setDocForm]=useState({title:"",description:"",document_type:"document",requires_approval:false});
 const [approvalForm,setApprovalForm]=useState({title:"",description:"",document_id:""});
 const [taskForm,setTaskForm]=useState({title:"",description:"",due_date:"",assigned_to:"client"});
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{const u=data.session?.user;if(!u){setLoading(false);return;}setUser(u);const {data:p}=await supabase.from("profiles").select("*").eq("id",u.id).single();setProfile(p);if(p?.role!=="admin"){setLoading(false);return;}const {data:c}=await supabase.from("client_accounts").select("*").order("company_name");setClients(c||[]);if(c?.[0])await choose(c[0]);setLoading(false);});},[]);
 async function choose(c:Row){setSelected(c);setNotice("");const [{data:d},{data:a},{data:t}]=await Promise.all([supabase.from("client_documents").select("*").eq("client_id",c.id).order("created_at",{ascending:false}),supabase.from("client_approvals").select("*").eq("client_id",c.id).order("requested_at",{ascending:false}),supabase.from("client_tasks").select("*").eq("client_id",c.id).order("created_at",{ascending:false})]);setDocs(d||[]);setApprovals(a||[]);setTasks(t||[])}
 async function uploadDocument(file:File){if(!selected||!user||!docForm.title.trim())return;setNotice("Uploading document...");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${selected.id}/${Date.now()}-${safe}`;const {error}=await supabase.storage.from("documents").upload(path,file);if(error){setNotice(error.message);return;}const {data,error:e}=await supabase.from("client_documents").insert({client_id:selected.id,uploaded_by:user.id,title:docForm.title.trim(),description:docForm.description.trim()||null,document_type:docForm.document_type,storage_path:path,file_name:file.name,mime_type:file.type,file_size:file.size,requires_approval:docForm.requires_approval}).select().single();if(e){setNotice(e.message);return;}if(data)setDocs(x=>[data,...x]);setDocForm({title:"",description:"",document_type:"document",requires_approval:false});setNotice("Document added.")}
 async function openDoc(d:Row){const {data,error}=await supabase.storage.from("documents").createSignedUrl(d.storage_path,300);if(error){setNotice(error.message);return;}window.open(data.signedUrl,"_blank")}
 async function createApproval(e:React.FormEvent){e.preventDefault();if(!selected||!user||!approvalForm.title.trim())return;const {data,error}=await supabase.from("client_approvals").insert({client_id:selected.id,title:approvalForm.title.trim(),description:approvalForm.description.trim()||null,document_id:approvalForm.document_id||null,requested_by:user.id}).select().single();if(error){setNotice(error.message);return;}if(data)setApprovals(x=>[data,...x]);setApprovalForm({title:"",description:"",document_id:""});setNotice("Approval request sent.")}
 async function createTask(e:React.FormEvent){e.preventDefault();if(!selected||!user||!taskForm.title.trim())return;const {data,error}=await supabase.from("client_tasks").insert({client_id:selected.id,title:taskForm.title.trim(),description:taskForm.description.trim()||null,due_date:taskForm.due_date||null,assigned_to:taskForm.assigned_to,created_by:user.id}).select().single();if(error){setNotice(error.message);return;}if(data)setTasks(x=>[data,...x]);setTaskForm({title:"",description:"",due_date:"",assigned_to:"client"});setNotice("Action item created.")}
 async function setTaskStatus(id:string,status:string){const {error}=await supabase.from("client_tasks").update({status}).eq("id",id);if(error){setNotice(error.message);return;}setTasks(x=>x.map(t=>t.id===id?{...t,status}:t))}
 if(loading)return <main className="wf-gate">LOADING PROJECT HUB...</main>;
 if(!user||profile?.role!=="admin")return <main className="wf-gate"><Link href="/portal">ADMIN SIGN IN REQUIRED</Link></main>;
 return <main className="wf-page"><header className="wf-head"><Link href="/admin"><ArrowLeft size={16}/> ADMIN</Link><img src="/assets/forged-logo-wide.webp" alt="Forged Digital"/><div className="wf-head-links"><Link href="/admin/billing">BILLING</Link></div></header><div className="wf-shell"><aside className="wf-clients"><p>PROJECT HUB</p><h2>CLIENTS</h2>{clients.map(c=><button key={c.id} className={selected?.id===c.id?"active":""} onClick={()=>choose(c)}><b>{c.company_name||c.contact_name||c.email}</b><span>{c.email}</span></button>)}</aside><section className="wf-main">{!selected?<div className="wf-empty">No clients yet.</div>:<><div className="wf-title"><p>SELECTED CLIENT</p><h1>{selected.company_name||selected.contact_name||selected.email}</h1><span>Documents, contracts, approvals, action items and client notifications.</span></div>{notice&&<div className="wf-notice">{notice}</div>}
 <section className="wf-card"><div className="wf-card-head"><FileText/><div><p>DOCUMENTS & CONTRACTS</p><h2>Shared Files</h2></div></div><div className="wf-form-grid"><input placeholder="Document title" value={docForm.title} onChange={e=>setDocForm({...docForm,title:e.target.value})}/><select value={docForm.document_type} onChange={e=>setDocForm({...docForm,document_type:e.target.value})}><option value="document">Document</option><option value="contract">Contract</option><option value="proposal">Proposal</option><option value="deliverable">Deliverable</option><option value="reference">Reference</option></select><input placeholder="Short description" value={docForm.description} onChange={e=>setDocForm({...docForm,description:e.target.value})}/><label className="wf-check"><input type="checkbox" checked={docForm.requires_approval} onChange={e=>setDocForm({...docForm,requires_approval:e.target.checked})}/> Requires approval</label><label className="wf-upload"><Upload size={15}/> UPLOAD FILE<input type="file" onChange={e=>e.target.files?.[0]&&uploadDocument(e.target.files[0])}/></label></div><div className="wf-list">{docs.length===0?<span>No documents yet.</span>:docs.map(d=><article key={d.id}><div><b>{d.title}</b><span>{d.document_type.toUpperCase()} · {d.file_name}</span></div><button onClick={()=>openDoc(d)}><Download size={14}/> OPEN</button></article>)}</div></section>
 <section className="wf-card"><div className="wf-card-head"><CheckCircle2/><div><p>CLIENT APPROVALS</p><h2>Request Approval</h2></div></div><form className="wf-form-grid" onSubmit={createApproval}><input required placeholder="Approval title" value={approvalForm.title} onChange={e=>setApprovalForm({...approvalForm,title:e.target.value})}/><select value={approvalForm.document_id} onChange={e=>setApprovalForm({...approvalForm,document_id:e.target.value})}><option value="">No linked document</option>{docs.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select><input placeholder="What needs approval?" value={approvalForm.description} onChange={e=>setApprovalForm({...approvalForm,description:e.target.value})}/><button type="submit">REQUEST APPROVAL</button></form><div className="wf-list">{approvals.length===0?<span>No approvals yet.</span>:approvals.map(a=><article key={a.id}><div><b>{a.title}</b><span>{a.description||"No notes"}</span></div><em className={`status ${a.status}`}>{a.status.replaceAll("_"," ")}</em></article>)}</div></section>
 <section className="wf-card"><div className="wf-card-head"><ListTodo/><div><p>ACTION ITEMS</p><h2>Tasks & Dependencies</h2></div></div><form className="wf-form-grid" onSubmit={createTask}><input required placeholder="Task title" value={taskForm.title} onChange={e=>setTaskForm({...taskForm,title:e.target.value})}/><select value={taskForm.assigned_to} onChange={e=>setTaskForm({...taskForm,assigned_to:e.target.value})}><option value="client">Client</option><option value="forged_digital">Forged Digital</option></select><input type="date" value={taskForm.due_date} onChange={e=>setTaskForm({...taskForm,due_date:e.target.value})}/><input placeholder="Task details" value={taskForm.description} onChange={e=>setTaskForm({...taskForm,description:e.target.value})}/><button type="submit">ADD ACTION ITEM</button></form><div className="wf-list">{tasks.length===0?<span>No action items yet.</span>:tasks.map(t=><article key={t.id}><div><b>{t.title}</b><span>{t.assigned_to==="client"?"CLIENT":"FORGED DIGITAL"}{t.due_date?` · Due ${new Date(t.due_date+"T00:00:00").toLocaleDateString()}`:""}</span></div><select value={t.status} onChange={e=>setTaskStatus(t.id,e.target.value)}><option value="open">Open</option><option value="in_progress">In Progress</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></article>)}</div></section>
 <section className="wf-card wf-info"><Bell/><div><h2>Notifications are automatic</h2><p>Clients are alerted when you add files, request approvals, or assign action items. You are alerted when they upload documents, answer approvals, or complete client tasks.</p></div></section>
 </>}</section></div></main>
}
